pr = "Präsens er/sie/es : "
pe = "Perfekt er/sie/es : "
verben = {
    "abbiegen": [pr + "biegt ab", pe + 'ist abgebogen'],
    "abfahren": [pr + 'fährt ab', pe + 'ist abgefahren'],
    "abfliegen": [pr + 'fliegt ab', pe + 'ist abgeflogen'],
    "abgeben": [pr + 'gibt ab', pe + 'hat abgegeben'],
    "abheben": [pr + 'hebt ab', pe + 'hat abgehoben'],
    "abnehmen": [pr + 'nimmt ab', pe + 'hat abgenommen'],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
    "": [pr + '', pe + ''],
}
inp = input('Enter : ')
for k, v in verben.items():
    if inp == k:
        print(k, v)
